name: 'publish'

# This will trigger the action on each push to the `release` branch.
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: install frontend dependencies
        run: pnpm install # change this to npm or pnpm depending on which one you use

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'LLaMazing v__VERSION__'
          releaseBody: |
            <img width="128" alt="app-icon" src="https://github.com/da-z/llamazing/blob/main/app-icon.png">
            
            ### New Features
                        
            ---
            
            **❗Note**: In order for the standalone app to work, you have to run Ollama server like this:
            
            ```shell
            $ OLLAMA_ORIGINS=* ollama serve
            ```
            
            Alternatively, set the property globally and restart Ollama server (does not persist system restart)
            
            ```shell
            $ launchctl setenv OLLAMA_ORIGINS '*'
            ```
          releaseDraft: true
          prerelease: false
